apiVersion: v1
kind: Namespace
metadata:
  name: enterprise-chatbot
  labels:
    name: enterprise-chatbot
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: enterprise-chatbot-quota
  namespace: enterprise-chatbot
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: enterprise-chatbot-limits
  namespace: enterprise-chatbot
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
