apiVersion: v1
kind: Namespace
metadata:
  name: org-chatbot
  labels:
    name: org-chatbot
    environment: production
    team: ai-platform
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: org-chatbot-quota
  namespace: org-chatbot
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
