name: ✨ Feature Request
description: Suggest a new feature or enhancement for the Org Chatbot
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! ✨
        
        Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: component
    attributes:
      label: 🏗️ Component
      description: Which component would this feature affect?
      options:
        - Frontend (React)
        - Backend (FastAPI)
        - AI Service (Ollama)
        - Database (PostgreSQL)
        - Cache (Redis)
        - Monitoring (Prometheus/Grafana)
        - Kubernetes/Helm
        - CI/CD Pipeline
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 🎯 Priority
      description: How important is this feature?
      options:
        - Critical (Must have)
        - High (Should have)
        - Medium (Nice to have)
        - Low (Future consideration)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature you'd like to see...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 🤔 Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or use case this feature would address...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe your proposed solution
      placeholder: Describe how you think this feature should work...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternative Solutions
      description: Any alternative solutions you've considered
      placeholder: Describe any alternative solutions or workarounds...

  - type: dropdown
    id: impact
    attributes:
      label: 📊 Impact
      description: Who would benefit from this feature?
      options:
        - All users
        - Enterprise users
        - Developers
        - Administrators
        - End users
        - Other
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: 📚 Examples
      description: Provide examples or mockups if applicable
      placeholder: If you have examples, mockups, or references, please include them here...

  - type: dropdown
    id: complexity
    attributes:
      label: ⚙️ Implementation Complexity
      description: How complex do you think this would be to implement?
      options:
        - Simple (1-2 days)
        - Medium (1-2 weeks)
        - Complex (1-2 months)
        - Very Complex (3+ months)
        - Not sure
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all the information requested above
          required: true
        - label: I am willing to help implement this feature
          required: false
        - label: I am willing to help test this feature
          required: false
