apiVersion: v2
name: org-chatbot
description: Enterprise AI-powered chatbot with advanced microservices architecture
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/username/org-chatbot
sources:
  - https://github.com/username/org-chatbot
maintainers:
  - name: Org Chatbot Team
    email: team@org-chatbot.com
keywords:
  - chatbot
  - ai
  - microservices
  - kubernetes
  - enterprise
annotations:
  category: AI/ML
  licenses: MIT
dependencies:
  - name: redis
    version: 17.3.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 12.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: prometheus
    version: 23.1.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: 6.50.7
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
